### ISSUE TITLE
Plotting Meta Issue

### ISSUE THREAD

**Issue by activexray** [kiranshila/Marconi.jl#2]
- [ ] Do something with y axis label
- [ ] Ability to set color list
- [ ] Surfaces?
- [ ] Group plots
- [ ] Polar plots
- [ ] Refactor plotting code to not reuse so much code
